[package]
name = "code-sonification"
version = "0.0.0"
edition = "2021"

[dependencies]
itertools = "0.11"
midly = "0.5"
rust-music-theory = "0.2"
swc_common = "0.31"
swc_ecma_ast = "0.106"
swc_ecma_parser = "0.136"
swc_ecma_visit = "0.92"
